// backend file that contains all the product data which is loaded dynamically to the screen

export default {
    products: [{
            _id: '1',
            name: 'Floral Print Frock',
            category: 'SmallGirl',
            image: '/image/product-1.webp',
            price: 650,
            brand: 'BIBA',
            rating: 4.7,
            numReviews: 15,
            countInStock: 10,
            description: 'Pink frock with lots of white flowers. Piping done with royal blue. It also have Angel Sleeves(elbow length).'
        },
        {
            _id: '2',
            name: 'Classic Frock',
            category: 'SmallGirl',
            image: '/image/product-2.jpg',
            price: 700,
            brand: 'Diva',
            rating: 4.1,
            numReviews: 10,
            countInStock: 11,
            description: 'Royal purple satin frock with embroidery work on the top. Sleeveless. A bow attached to the waist.'
        },
        {
            _id: '3',
            name: 'Casual Lace Dress',
            category: 'YoungWoman',
            image: '/image/product-3.jpg',
            price: 950,
            brand: 'Diva',
            rating: 4.8,
            numReviews: 8,
            countInStock: 6,
            description: 'Cobalt blue lace dress. It is an A-line, knee-length dress with an illusion neckline.'
        },
        {
            _id: '4',
            name: 'Empire Dress',
            category: 'YoungWoman',
            image: '/image/product-4.webp',
            price: 1000,
            brand: 'H&M',
            rating: 3.4,
            numReviews: 13,
            countInStock: 8,
            description: 'A pastel green empire dress with surplice neckline. Knee length dress with buttons for a chic look.'
        },
        {
            _id: '5',
            name: 'Cocktail Midi Dress',
            category: 'YoungWoman',
            image: '/image/product-5.jpg',
            price: 950,
            brand: 'H&M',
            rating: 3.8,
            numReviews: 15,
            countInStock: 5,
            description: 'Bright pink cocktail midi with stoop neckline. Tea length dress with white printed pattern.'
        },
        {
            _id: '6',
            name: 'Colorful Maxi Dress',
            category: 'YoungWoman',
            image: '/image/product-6.jpg',
            price: 800,
            brand: 'BIBA',
            rating: 4.9,
            numReviews: 25,
            countInStock: 19,
            description: 'Clinched waist multicolor dress. Tea length dress with a boat neckline and sleeveless.'
        },
        {
            _id: '7',
            name: 'Fit Slim T-Shirt',
            category: 'YoungMan',
            image: '/image/product-7.jfif',
            price: 650,
            brand: 'Jockey',
            rating: 3.7,
            numReviews: 20,
            countInStock: 9,
            description: 'Slim fit T-Shirt with solid grey color. Round neckline and fine fabric.'
        },
        {
            _id: '8',
            name: 'Printed T-Shirt',
            category: 'YoungMan',
            image: '/image/product-8.jpg',
            price: 790,
            brand: 'BIBA',
            rating: 4.7,
            numReviews: 13,
            countInStock: 10,
            description: 'White printed T-Shirt with round neckline. Skull design with other elements.'
        },
        {
            _id: '9',
            name: 'Printed Pants',
            category: 'AdultMan',
            image: '/image/product-9.jpg',
            price: 1100,
            brand: 'Jockey',
            rating: 4.2,
            numReviews: 18,
            countInStock: 17,
            description: 'Neostreak silm fit stretchable jeans or pants. Yellow base with brown checks on it.'
        },
        {
            _id: '10',
            name: 'Formal Pants',
            category: 'AdultMan',
            image: '/image/product-10.jpg',
            price: 1099,
            brand: 'Jockey',
            rating: 3.8,
            numReviews: 21,
            countInStock: 13,
            description: 'Jaypore wine elasticated length modal pants. Perfect fit for formal purpose.'
        },
        {
            _id: '11',
            name: 'Boys Casual',
            category: 'ToddlerBoy',
            image: '/image/product-11.jpeg',
            price: 999,
            brand: 'FirstCry',
            rating: 3,
            numReviews: 60,
            countInStock: 13,
            description: 'Casual Clothes for toddler boy. Letter printed Hoodie for winters in black and olive green.'
        },
        {
            _id: '12',
            name: 'Red Shirt',
            category: 'ToddlerBoy',
            image: '/image/product-12.jfif',
            price: 1079,
            brand: 'Bee Merry',
            rating: 4.2,
            numReviews: 8,
            countInStock: 10,
            description: 'Tartan Plaid toddler boys shirt. Chic red with blue checks over it. Best fit with jeans.'
        },
        {
            _id: '13',
            name: 'Toddler Dress',
            category: 'ToddlerGirl',
            image: '/image/product-13.jfif',
            price: 899,
            brand: 'FirstCry',
            rating: 3.1,
            numReviews: 56,
            countInStock: 19,
            description: 'Long Sleeves Fancy Dress for toddlers. Butterflies on royal blue with rainbow sleeves and empire line.'
        },
        {
            _id: '14',
            name: 'Dress Set',
            category: 'ToddlerGirl',
            image: '/image/product-14.jpeg',
            price: 699,
            brand: 'Jockey',
            rating: 4.8,
            numReviews: 65,
            countInStock: 10,
            description: 'Spring hue Unicorn toddler girls cotton tunic tops dress with pants. Long sleeves and baby pink.'
        },
        {
            _id: '15',
            name: 'Polka Dot Saree',
            category: 'AdultWoman',
            image: '/image/product-15.jpg',
            price: 499,
            brand: 'Laxmii',
            rating: 2.4,
            numReviews: 15,
            countInStock: 23,
            description: 'Polka dot half and half Georgette saree. Contrasting black and yellow for vibrant design.'
        },
        {
            _id: '16',
            name: 'Silk Saree',
            category: 'AdultWoman',
            image: '/image/product-16.jpg',
            price: 2599,
            brand: 'Laxmii',
            rating: 5,
            numReviews: 29,
            countInStock: 4,
            description: 'Almond pink colored beige border silk saree for woman. Classy faux saree fit for any occasions.'
        },
        {
            _id: '17',
            name: 'Designer Suit',
            category: 'AdultWoman',
            image: '/image/product-17.jpg',
            price: 898,
            brand: 'Zara',
            rating: 3.8,
            numReviews: 21,
            countInStock: 8,
            description: 'Teal cotton Silk stitched suit with dupatta. Deep blue with classic thread work. Floral dupatta.'
        },
        {
            _id: '18',
            name: 'Rosatro T-Shirt',
            category: 'AdultMan',
            image: '/image/product-18.jpg',
            price: 650,
            brand: 'Polo',
            rating: 1.4,
            numReviews: 35,
            countInStock: 7,
            description: 'Patterned T-Shirt by Polo. Collar neck with buttons. Half sleeves.'
        },
        {
            _id: '19',
            name: 'Checked Shirt',
            category: 'AdultMan',
            image: '/image/product-19.jpg',
            price: 450,
            brand: 'Raymonds',
            rating: 0.67,
            numReviews: 21,
            countInStock: 5,
            description: 'Yellow and blue checked shirt upon white base. Comfortable and formal.'
        },
        {
            _id: '20',
            name: 'Hot Pants',
            category: 'YoungWoman',
            image: '/image/product-20.webp',
            price: 700,
            brand: 'H&M',
            rating: 4,
            numReviews: 21,
            countInStock: 21,
            description: 'Demin short jeans or pants light blue. Waist-line and ripped at bottom.'
        },
        {
            _id: '21',
            name: 'Crop Top',
            category: 'YoungWoman',
            image: '/image/product-21.webp',
            price: 850,
            brand: 'Diva',
            rating: 4.7,
            numReviews: 98,
            countInStock: 17,
            description: 'Grey textured crop top. Off-Shoulder with designed full-sleeves. Perfect with high-waist jeans.'
        },
        {
            _id: '22',
            name: 'Sports Jersey',
            category: 'YoungMan',
            image: '/image/product-22.jpg',
            price: 400,
            brand: 'Polo',
            rating: 2.5,
            numReviews: 45,
            countInStock: 9,
            description: 'Ombre print polo T-shirt. Slim fit, half-sleeves, sports jersey.'
        },
        {
            _id: '23',
            name: 'Summer Pants',
            category: 'YoungMan',
            image: '/image/product-23.webp',
            price: 1099,
            brand: 'Jockey',
            rating: 3.2,
            numReviews: 27,
            countInStock: 10,
            description: 'Summer fit black pants with print at bottom and string designed at the sides.'
        },
        {
            _id: '24',
            name: 'Demin Dungary',
            category: 'ToddlerBoy',
            image: '/image/product-24.jpg',
            price: 2000,
            brand: 'FirstCry',
            rating: 4.8,
            numReviews: 78,
            countInStock: 20,
            description: 'Children demin dungary for toddler boys. Blue slim leg with vintage texure.'
        },
        {
            _id: '25',
            name: 'Skirt-Top',
            category: 'SmallGirl',
            image: '/image/product-25.jpg',
            price: 1100,
            brand: 'H&M',
            rating: 3,
            numReviews: 21,
            countInStock: 7,
            description: 'Belly summer crop top and stirk for girls. Sleeveless and neckless attached. Cool blue in color.'
        },
    ],
};